### ISSUE TITLE
Een aantal feature detects ontbreken nog

### ISSUE THREAD

**Issue by krijnhoetmer** [sayLISA/saylisa.github.io#10]
Je gebruikt browser APIs waar je niet op test (bijvoorbeeld `classList` en `addEventListener`), dus dit kan stuk gaan in sommige browsers. Hoe voorkom je dit?

**Comment by sayLISA** [comment]
Je kunt die op verschillende manieren voorkomen. In mijn code gebruik ik bijvoorbeeld classList om een element op display none te zetten, dit betekend dus dat hij altijd zichtbaar is ook op het moment dat classList niet werkt, hier wordt de site iets minder mooi van maar het gaat niet kapot. 

Daarnaast kun je een feature detect doen of de API’s ondersteund worden, worden deze niet ondersteund kun je het op een andere manier schrijven. Je kunt het ook zonder feature detect oplossen. Voor classList kun je bijvoorbeeld een polyfill gebruiken, dit is niet heel handig als je zoals ik heb maar 1 line code hebt voor classList want dan voeg je veel onnodige code toe. Je kunt ook bijvoorbeeld className gebruiken wat door meer browsers ondersteund wordt. 

addEventlistener wordt in de meeste browsers ondersteund maar in bijvoorbeeld IE versie 9 en daaronder heeft zijn eigen methode: attachEvent. Om het helemaal voor elke browser werkend te maken kun je in je HTML de onclick=”” property erin zetten, dit wordt door alle browsers ondersteund die ook Javascript ondersteunen.

**Comment by krijnhoetmer** [comment]
En voor welke oplossing ga jij kiezen?

**Comment by sayLISA** [comment]
Ik heb nu in plaats van classList className gebruikt, omdat ik maar aan 1 element een class toevoeg en er verder niks mee doe dus is dit ook prima bruikbaar. Het is in ongeveer alle browsers ondersteund (IE6+, Firefox 2+, Chrome 1+ etc).

Voor addEventListener heb ik een check toegevoegd zodat het ook werkt in oudere IE browsers. if(document.addEventListener){ --> gebruik addEventListener } else{ --> gebruik attachEvent }
(met attachEvent & addEventListener kun je meer events aan een element koppelen, met alleen onclick  niet, daarom heb ik ervoor gekozen toch addEventListener te blijven gebruiken om niet in de problemen te komen in het geval je de code wilt uitbreiden)

**Comment by KoopReynders** [comment]
done
