### ISSUE TITLE
Wat doet data-number als JS niet beschikbaar is?

### ISSUE THREAD

**Issue by krijnhoetmer** [sayLISA/saylisa.github.io#11]
Probeer voor je `<input>` elementen een attribuut te vinden dat ook iets doet voor de server, en hergebruik dat attribuut in je code. Scheelt weer een non-standard attribuut uitvinden en maakt je code beter bruikbaar voor een back-end ontwikkelaar.

**Comment by sayLISA** [comment]
Ik heb data-number weggehaald en in plaats hiervan het name attribuut erin gezet. Het naam attribuut kun je gebruiken om de data uit een formulier te herkennen op de server. Je kunt bijvoorbeeld met het naam attribuut weer data van de server halen met een GET request. Nu heeft het dus geen onnodige attributen meer.
