### ISSUE TITLE
JS foutmelding als je klikt op een t-shirt

### ISSUE THREAD

**Issue by krijnhoetmer** [sayLISA/saylisa.github.io#12]
Als je op iets anders dan de knop klikt, krijg je in je console een foutmelding. Probeer je JS zo te maken dat je die error nooit krijgt.

**Comment by sayLISA** [comment]
Ik heb in de code een if statement toegevoegd die checkt of het element waarop geklikt wordt het element is dat iets uit moet voeren (namelijk de submit buttons): if (e.target.tagName == 'INPUT'). Als dit waar is voert ie de code uit die elementen toevoegt aan de favorieten lijst, anders doet hij niks. Nu is er geen error meer als je op een ander element klikt dan de submit buttons.

**Comment by KoopReynders** [comment]
done
