### ISSUE TITLE
e.preventDefault() op een onhandige plek

### ISSUE THREAD

**Issue by krijnhoetmer** [sayLISA/saylisa.github.io#13]
Je gebruikt nu `e.preventDefault()` niet op een handige plek. Wat gebeurt er als er daaronder alsnog iets verkeerd gaat in je script?

**Comment by sayLISA** [comment]
Staat nu onderaan in de if statement die kijkt of het een INPUT element is waar je op klikt in het click event. Daar is eigenlijk alle andere code al uitgevoerd, en voegt ie alleen nog dingen toe aan de favorieten lijst via Javascript.

**Comment by KoopReynders** [comment]
done
