### ISSUE TITLE
Demo is niet responsive

### ISSUE THREAD

**Issue by krijnhoetmer** [sayLISA/saylisa.github.io#9]
Op kleinere schermen werkt 'ie niet heel lekker.

**Comment by sayLISA** [comment]
Ik was de <meta name="viewport" content="width=device-width, initial-scale=1"> tag vergeten, pakt nu het goede formaat op kleine schermen.

http://saylisa.github.io/browser-tech/week-3/

**Comment by KoopReynders** [comment]
done
